[package]
name = "demo-web"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["flex"]
flex = ["burn/flex"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { version = "0.22.0-pre.3", default-features = false, features = ["extension"] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
